### ISSUE TITLE
No Virus.

### ISSUE THREAD

**Issue by kurimanju-dev** [PETEROLO291/G-CPS#1]
Wrong Project....

**Comment by PETEROLO291** [comment]
I mean, its open source, you can perfectly read the code and see that there is noting bad on the code.

**Comment by kurimanju-dev** [comment]
Omg, i'm so sorry. This was the wrong project.... 
Just saw it now....
I downloaded a other Cps software from github which was a virus. But it got already deleted.

**Comment by PETEROLO291** [comment]
Ah okay, hahaha, that annoyed me a bit to read that comment. Happy to know that all it was is a error :D.
