### ISSUE TITLE
PySimpleGUI Settings APIs may be of interest

### ISSUE THREAD

**Issue by PySimpleGUI** [PETEROLO291/G-CPS#2]
Thank you for the mention in your readme!  It helps other people find what magic you used to get a GUI 😉

I see that you store your theme in a text file.

If you use the "User Settings APIs" in PySimpleGUI, then you can store the setting from one session to another and also have a default setting if one isn't found.  There are a lot of examples now in using this API.

To get the theme when you start:

```python
theme = sg.user_settings_get_entry('-theme-', 'Dark Amber')
```

To change it, you "set" the entry:
```python
sg.user_settings_set_entry('-theme-', new_theme)
```

The settings are saved to and read from a JSON file automatically.  A "get" is 1 line of code and can be used directly in layouts.

I like that you're making these GUIs and publishing your code.  Nice work.

**Comment by PETEROLO291** [comment]
Ok, thanks! I'll see what I can do, so far I have only experimented a bit with a few API
